### ISSUE TITLE
System.exit in case of an exception in KafkaProducer

### ISSUE THREAD

**Issue by yveshauser** [softwaremill/reactive-kafka#10]
https://github.com/softwaremill/reactive-kafka/blame/master/src/main/scala/kafka/producer/KafkaProducer.scala#L93

Could you handle exceptions in the producer other than System.exit?

**Comment by kciesielski** [comment]
This part of code comes from another library: https://github.com/stealthly/scala-kafka/blob/master/src/main/scala/KafkaProducer.scala, I guess I missed this weird `System.exit()` from the beginning.
Thanks for pointing that out, there are obviously better ways to handle this ;)
