### ISSUE TITLE
com.softwaremill.react.kafka2 package missing 

### ISSUE THREAD

**Issue by concerned3rdparty** [softwaremill/reactive-kafka#102]
When I fetched reactivekafka with the dependency below, i could not see kafka2 package under com.softwaremill.react. I wanted to use Producer.value2record method just to convert an integer list source to producerrecord.
libraryDependencies += "com.softwaremill.reactivekafka" %% "reactive-kafka-core" % "0.10.0"

**Comment by 13h3r** [comment]
`kafka2` package is under development right now and not included in 0.10.0. You can build version from master to get new functionality.

**Comment by kciesielski** [comment]
@concerned3rdparty It has been deliberately excluded from last release, it's an experimental and evolving part of the API.
