### ISSUE TITLE
Akka streams 1.0

### ISSUE THREAD

**Issue by alexanderzafirov** [softwaremill/reactive-kafka#19]
Are you planning on bumping the version to the official release 1.0? Maybe you weren't aware - they released it two days ago :)

https://groups.google.com/forum/#!topic/akka-user/iROrl6PB2jY

**Comment by kciesielski** [comment]
Yup, I'm aware. I'm currently working on finishing some major API refactoring. Maybe I'll switch to akka-stream 1.0 and at least release a snapshot until the refactoring is done.

**Comment by alexanderzafirov** [comment]
Looking forward!

**Comment by kciesielski** [comment]
Hi @alexanderzafirov, 0.7.0-SNAPSHOT with akka-streams 1.0 is now published. I'm only publishing SNAPSHOTs in some exceptional cases like this one, so you can consider this safe :)
