### ISSUE TITLE
Any plans for Producer/Consumer using org.apache.kafka.clients?

### ISSUE THREAD

**Issue by unitymind** [softwaremill/reactive-kafka#26]
Firstly, thank you for your work with reactive-kafka!

Secondary, I ran with limitation of integration [Confluent Kafka Avro Serialization](http://docs.confluent.io/1.0/app-development.html) and [Confluent Schema Registry](http://docs.confluent.io/1.0/schema-registry/docs/serializer-formatter.html) using old Producer/Consumer (which writing in Scala). According to Kafka documentation:

> As of 0.8.2 Kafka includes a newly rewritten Java producer. The next release will include an equivalent Java consumer. These new clients are meant to supplant the existing Scala clients, but for compatability they will co-exist for some time. These clients are available in a seperate jar with minimal dependencies, while the old Scala clients remain packaged with the server.

Integration with new Producer/Consumer would require a change how the reactive-kafka will be configured, as well a internal implementation of `KafkaActorPublisher` and `KafkaActorSubscriber`. I am not see the paths how to not break user-api.

Any thoughts?

**Comment by unitymind** [comment]
Ouch, seems like new Consumer not yet fully implemented and migration make sense only after 0.9 release

**Comment by kciesielski** [comment]
That's right. I'm keeping my eye on this, because this new consumer looks pretty promising :)

**Comment by sslavic** [comment]
Kafka 0.9.0.0 RC1 is out http://mail-archives.apache.org/mod_mbox/kafka-users/201511.mbox/%3CCAFc58G-qph4BXA1FZ%3D74gwiEvLr01kNQ_2Fuh-xRZJtDYfTa5A%40mail.gmail.com%3E

**Comment by kciesielski** [comment]
Thanks, @sslavic :) Looks like it's time for a branch and some tinkering with the new consumer.

**Comment by kciesielski** [comment]
Implemented in 0.9
