### ISSUE TITLE
Offset management

### ISSUE THREAD

**Issue by adamw** [softwaremill/reactive-kafka#3]
Currently the streaming always starts from the start of the topic, as far as I understand the code. It would be good to have some sort of offset management:
- as a starter, making it possible to stream from the end of a topic could be useful
- Kafka can store the last-consumed offset to make the topic behave as a point-to-point messaging system (see https://kafka.apache.org/documentation.html#semantics). Storing the streamed offsets could be a first step
- finally, an at-least-once-delivery option could be realised by accepting a stream of consumed offsets, and writing only the highest consumed offset. This could be very useful, but also hard to implement probably :)

**Comment by lu4nm3** [comment]
+1

**Comment by singhmgithub** [comment]
:+1:

**Comment by singhmgithub** [comment]
+1

**Comment by filosganga** [comment]
It is needed to store only the last safe consumed offset (the bigger offset is possible to commit without losing messages) and the offset of the message being procesed. 

I did it in a custom Kafka consumer. You need also to keep the last consumed offset to avoid resending already published offset.

**Comment by adamw** [comment]
But how do you know what's the last "safe" consumed offset? This needs to come from the consumer somehow. You can't exactly-once delivery as there are no transactions here (so you either agree to loose messages, as it is now, or you can accept duplicates)

**Comment by filosganga** [comment]
You are right, akka stream does not permit to do that. In fact I have
applied this technique to my previous project which was not akka stream
powered.

I think the only possible way in akka stream is to tune the subscriber,
aware of what happen in the publisher, using a custom RequestStrategy. When
the Publisher receive a new Request message, you can assume that the
previous messages have been processed. But of course it is far from be
reliable.

On 18 April 2015 at 13:02, Adam Warski <notifications@github.com> wrote:

> But how do you know what's the last "safe" consumed offset? This needs to
> come from the consumer somehow. You can't exactly-once delivery as there
> are no transactions here (so you either agree to loose messages, as it is
> now, or you can accept duplicates)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softwaremill/reactive-kafka/issues/3#issuecomment-94161193>
> .
>



-- 

[image: --]
Filippo De Luca
[image: http://]about.me/FilippoDeLuca
<http://about.me/FilippoDeLuca?promo=email_sig>

**Comment by adamw** [comment]
Or you could provide a `Subscriber[Long]` to which consumed offsets should be published. That way the consumer can provide a back-stream with the right information. Only constraint is that the offsets would have to be consumed in-order.

**Comment by filosganga** [comment]
It is very similar to what I did, the difference is that the ordered constraint
was not strict, because with some trick you can store this information in a
data structure that permit you to extract the highest continuous offset
processed.

The drawback of this is that you have to piggyback the offset for the whole
stream. While akka stream already provide a sort of ack mechanism using the
RequestStrategy.

On 18 April 2015 at 13:10, Adam Warski <notifications@github.com> wrote:

> Or you could provide a Subscriber[Long] to which consumed offsets should
> be published. That way the consumer can provide a back-stream with the
> right information. Only constraint is that the offsets would have to be
> consumed in-order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softwaremill/reactive-kafka/issues/3#issuecomment-94161917>
> .
>



-- 

[image: --]
Filippo De Luca
[image: http://]about.me/FilippoDeLuca
<http://about.me/FilippoDeLuca?promo=email_sig>

**Comment by adamw** [comment]
Another approach: the `Source` would be a stream of `Message[T]`, which would contain, apart from the `T` instance itself, a `consumed()` callback, which would write the offset information back to Kafka/Zookeeper. Now the client would have a lot of choices on how to signal that messages have been consumed. It could be done synchronously with processing the message (but that would be slow). Or the stream of incoming messages could be transformed to a stream of `() => consumed()` functions, which would be gathered in 1-second blocks and only the last one would be confirmed. Or the stream could be split and the acknowledgments could be asynchronous.

On the other hand, when sending messages to Kafka, we could get a stream of futures, which would be completed when the messages are sent, but that's another issue :)

**Comment by hepin1989** [comment]
+3

**Comment by filosganga** [comment]
Hi Adam,
It is the approach I have used in my custom kafka consumer actor. To me it
is a good solution.

On 2 July 2015 at 08:40, Adam Warski <notifications@github.com> wrote:

> Another approach: the Source would be a stream of Message[T], which would
> contain, apart from the T instance itself, a consumed() callback, which
> would write the offset information back to Kafka/Zookeeper. Now the client
> would have a lot of choices on how to signal that messages have been
> consumed. It could be done synchronously with processing the message (but
> that would be slow). Or the stream of incoming messages could be
> transformed to a stream of () => consumed() functions, which would be
> gathered in 1-second blocks and only the last one would be confirmed. Or
> the stream could be split and the acknowledgments could be asynchronous.
>
> On the other hand, when sending messages to Kafka, we could get a stream
> of futures, which would be completed when the messages are sent, but that's
> another issue :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softwaremill/reactive-kafka/issues/3#issuecomment-117946048>
> .
>



-- 

[image: --]
Filippo De Luca
[image: http://]about.me/FilippoDeLuca
<http://about.me/FilippoDeLuca?promo=email_sig>

**Comment by llaakes** [comment]
We are currently prototyping an app using reactive-kafka but really need offset management so we can minimize reprocessing of messages in a topic by a clusters of clients, and so we can continue at last offset in case of system restart. 

What is the current status offset managment in reactive-kafka?  

In a test client I have the current setup, but on client restart it restarts reading the entire topic rather then where it last left off.

```scala
    val props = ConsumerProperties(
      brokerList = brokerList,
      zooKeeperHost = zooKeeperHost,
      topic = desc.topic,
      groupId = client,
      decoder = new StringDecoder()
    ).kafkaOffsetsStorage(dualCommit = true)
    props.setProperty("auto.commit.interval.ms", "1000")
    props.setProperty("auto.commit.enable", "true")
```

**Comment by kciesielski** [comment]
@llaakes currently I am waiting for Kafka 0.9 with new Consumer API that would allow easier manual commit/offset management. However, Adam's solution from above may be a good idea to implement in the meantime. For your purpose - maybe you could use `ConsumerProperties.readFromEndOfStream()`?

**Comment by kciesielski** [comment]
Looks like the new API is scheduled for 0.8.3 (Oct 2015), so maybe I can take a deeper look to tailor something custom earlier just to allow manual commits.

**Comment by llaakes** [comment]
@kciesielski thanks for the quick response.  It looks like, using the ConsumerProperties listed above, reactive-kafka already writes the offset to Kafka, If I wait about 30 seconds (longer than spec'd above for some reason) I see the offset for the topic in Consumers.  If I then stop and restart the test client (which generates new messages and consumes them, it continues from the last read.  It appears offsets are being used, am I missing something?

**Comment by kciesielski** [comment]
@llaakes consumer properties are immutable and the `setProperty` method returns a new object, so you should probably do:
```Scala
    val props = ConsumerProperties(
      brokerList = brokerList,
      zooKeeperHost = zooKeeperHost,
      topic = desc.topic,
      groupId = client,
      decoder = new StringDecoder()
    )
      .kafkaOffsetsStorage(dualCommit = true)
      .setProperty("auto.commit.interval.ms", "1000")
      .setProperty("auto.commit.enable", "true")
```
You can skip the last one because auto-commit is the default setting.

**Comment by Semptic** [comment]
Your new commit handling seems promising, but with this solution it would be nice to get a way to send the message to a `KafkaProducer` before commiting. This could be done manually but thats not handy. A nicer solution would if we can get a `Flow` for a `KafkaProducer`. 

I think this can easily be done by adding a custom message to `KafkaActorSubscriber`. 

Something like

```scala
class KafkaActorSubscriber [...] {
  [..]
  def receive: {
   [...]
   case Msg(msg) =>
     process(msg)
     sender() ! msg
}
```

```scala
val sendToKafka = Flow[T]
  .mapAsync(msg => (actor ?  Msg(msg)).mapTo[T])
```
Now you can use it like:

```scala
Source(consumerWithOffsetSink.publisher)
    .map(processMessage(_)) // your message processing
    .via(sendToKafka)
    .to(consumerWithOffsetSink.offsetCommitSink) // stream back for commit
    .run()
```

Or use the `KafkaProducer` directly in the `Flow`

**Comment by kciesielski** [comment]
@Semptic this looks like bypassing streams by sending a message manually to an actor. A `KafkaProducer` conceptually is not a `Flow` because it just puts messages in the log. Your case seems to be a candidate for building a graph with splitted stream, where one branch puts to one sink (`Kafka`), and the second one putting back to the `offsetCommitSink`.

**Comment by Semptic** [comment]
Thx, seams to be a good solution (in combination with `.commitInterval(x seconds)`)
