### ISSUE TITLE
should recreate KafkaProducer once actor restart

### ISSUE THREAD

**Issue by hepin1989** [softwaremill/reactive-kafka#30]
the current code have a bug that once there is an exception occur,the``` KafkaActorSubscriber``` is restarted ,and then cause the producer was passed in and was closed then it will cause exception of ```producer already closed ```,and will trap the subscriber.

**Comment by hepin1989** [comment]
my bad seems:)

**Comment by hepin1989** [comment]
but the problem is still there,I will come up with a proper fix.

**Comment by kciesielski** [comment]
See my comment on https://github.com/softwaremill/reactive-kafka/issues/29

**Comment by kciesielski** [comment]
@hepin1989 I just added some more changes. Now even with default error handling the underlying resources will not be closed on restart. Coming in 0.8.0
