### ISSUE TITLE
KafkaActorSubscriber should handle specially to ProducerClosedException

### ISSUE THREAD

**Issue by hepin1989** [softwaremill/reactive-kafka#31]
if it cause the restart,then the error will continue shows up.
a better way I think should be handle it specially,stop it quickly or restart with a new producer.

**Comment by kciesielski** [comment]
See my comment to #29

**Comment by hepin1989** [comment]
yes,thanks I will close it for now ,cause it's a design decision.
thanks

**Comment by kciesielski** [comment]
@hepin1989 I just added some more changes. Now even with default error handling the underlying resources will not be closed on restart. Coming in 0.8.0

**Comment by hepin1989** [comment]
@kciesielski thanks,I am using your project to stream the akka logging as protobuf to kafka and then pump it to graylog on another node.thanks
