### ISSUE TITLE
add recheck interval when there is no more data for any specified topic

### ISSUE THREAD

**Issue by hepin1989** [softwaremill/reactive-kafka#32]
https://github.com/softwaremill/reactive-kafka/blob/master/src/main/scala/com/softwaremill/react/kafka/KafkaActorPublisher.scala#L33

I think we should add a property that when there is no more data for any specified topic,then we could reschedule the check after a period of time.like ```recheckInterval```?

otherwise I see a lot of traffic there even there is no more data.

**Comment by kciesielski** [comment]
Hi @hepin1989, I guess this issue can be closed? :)

**Comment by hepin1989** [comment]
yes,I think so,it's very old.
