### ISSUE TITLE
Native committer fails to work after broken connection

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/reactive-kafka#43]
A problem has been reported by @cleliofs:

Hi, we are having a problem on the offset committer `(com.softwaremill.react.kafka.commit.native.NativeCommitFailedException: Failed to commit after 5 retires)`. Since last week we lost the commits for a specific topic (other topics seem to been committed fine) and the current offset commit lag is in the magnitude of ~ 100k. This error message is thrown every 5 secs (based on the commit interval as explained below).
The underlining exception java.io.IOException: Broken pipe, the last Reactive Code before this exception is thrown is at `kafka.network.BoundedByteBufferSend.writeTo(BoundedByteBufferSend.scala:56)`
The pain is that once it gets into that stage of `NativeCommitFailedException` it never recovers, I mean all offset commits keep failing, which it is a bit strange if we consider a temporary communication issue that should be sorted after sometime?

**Comment by cleliofs** [comment]
thanks! @kciesielski which release version will contain this fix?

**Comment by kciesielski** [comment]
@cleliofs 0.8.2, coming as soon as I add some more tests

**Comment by cleliofs** [comment]
Just to say this fix has been working fine in our Production servers since we released (2 weeks ago) - thanks @kciesielski

**Comment by kciesielski** [comment]
@cleliofs Thanks for reporting back. Did you notice any "Failed to commit offsets" entries in your logs and then succesfull restarts?

**Comment by cleliofs** [comment]
Actually, so far we did not have any "failed to commit offsets" messages in our logs - the unique log messages regard Kafka offsets are these:

```
logs/streams.2015-11-05.0.log:2015-11-05 11:56:34,282 [main] INFO  k.c.ZookeeperConsumerConnector - [dde-streams_ip-172-31-21-246-1446724593528-999a2954], Committing all offsets after clearing the fetcher queues
logs/streams.2015-11-05.0.log:2015-11-05 11:58:02,062 [dde-streams_ip-172-31-21-246-1446724593528-999a2954_watcher_executor] INFO  k.c.ZookeeperConsumerConnector - [dde-streams_ip-172-31-21-246-1446724593528-999a2954], Committing all offsets after clearing the fetcher queues
```

But, these are from Kafka lib itself. I will keep an eye on that and make sure the offsets are being committed fine. So far so good, no problem. Thanks!
