### ISSUE TITLE
Akka Streams 2.0-M1?

### ISSUE THREAD

**Issue by tdrozdowski** [softwaremill/reactive-kafka#48]
Looks like Akka Streams 1.0 is deprecated and the site documentation recommends migrating to version 2.0.  Do you have a branch that is tracking this?

**Comment by adamw** [comment]
It's been only a few hours since 2.0-M1 release (which is only a milestone), so I suppose no branch yet ;)

**Comment by kciesielski** [comment]
Right :) I guess a branch will be reasonable as soon as 2.0 approaches RC.

**Comment by ktoso** [comment]
Proposing to rename title of ticket to talk about `2.0-M1`? It's a very specific thing, there is no 2.0 out yet so it may confuse people.

**Comment by MadeInChina** [comment]
+1

**Comment by victorvillena** [comment]
I forked the repo to test an upgrade to Akka Streams 2.0-M1, everything looks good as of now.

**Comment by kciesielski** [comment]
Great to hear that. Thanks for your effort @victorvillena :)

**Comment by pkinsky** [comment]
Akka Streams 2.0 was released today: http://akka.io/news/2015/12/21/akka-streams-2.0-released.html

**Comment by kciesielski** [comment]
Thank @pkinsky. I did some initial checks and it looks promising, probably transition is going to be smooth.

**Comment by kciesielski** [comment]
Implemented in 0.8.4 and 0.9.0

**Comment by tdrozdowski** [comment]
So quickly after 2.0 was released, 2.0.1 was released, so we need one more update please. :)

**Comment by kciesielski** [comment]
@tdrozdowski 2.0.1 adds a fix that doesn't affect compatibility with reactive-kafka, so you should be able to set this version safely in your own dependencies. I will bump accordingly and add it to the next release.
