### ISSUE TITLE
Support Topic Filters

### ISSUE THREAD

**Issue by pcleary00** [softwaremill/reactive-kafka#6]
I need to be able to setup a stream using topic filters.

The idea is to be able to setup a Consumer Group given a topic filter.  In turn, we want to be able to consume messages from each topic that matches the filter.

I am going to be using Reactive Streams for the processing the messages.  If there is something already in the works, it would be great.  Otherwise, perhaps I can create a PR.  I wasn't sure what the status was with the Simple Consumer work.

**Comment by kciesielski** [comment]
Current implementation is based on the `kafka.consumer.Whitelist` filter. When you use the `ReactiveKafka` API, you can provide topic name or a *regex*. Is that sufficient for your needs?

**Comment by pcleary00** [comment]
Ok, great, yea, regex would work fine.
