### ISSUE TITLE
Add capability of subscribing to specific topic partitions

### ISSUE THREAD

**Issue by mjkrumlauf** [softwaremill/reactive-kafka#61]
The new KafkaConsumer API provides the capability of subscribing to individual partitions within a topic.  Requesting that this capability be exposed, perhaps through the **ReactiveKafkaConsumer** class.

See https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html, **Subscribing to Specific Partitions** for more details.

**Comment by danielwegener** [comment]
This, together with #62 would solve #5

**Comment by 13h3r** [comment]
Already in master?

**Comment by mjkrumlauf** [comment]
Yes - closing issue.
