### ISSUE TITLE
Add capability of consuming from an application-specified offset

### ISSUE THREAD

**Issue by mjkrumlauf** [softwaremill/reactive-kafka#62]
Make use of _KafkaConsumer.seek(TopicPartition, long)_ to allow the consuming application to start consuming a topic from a specified offset.  This would be extremely useful in providing yet more decoupling of producers from consumers.

See https://kafka.apache.org/090/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

**Comment by danielwegener** [comment]
This, together with #61 would solve #5

**Comment by kciesielski** [comment]
Thanks @mjkrumlauf, this is an important feature to cover.

**Comment by bchazalet** [comment]
+1

**Comment by 13h3r** [comment]
Looks like this already in master

**Comment by mjkrumlauf** [comment]
Yes - closing issue.
