### ISSUE TITLE
Consumption of messages pause after 10mins

### ISSUE THREAD

**Issue by dmtrs** [softwaremill/reactive-kafka#65]
In my application I create 3 consumers each consuming from 8 partitions (total 24).
Application runs smoothly by consuming message for around 10mins from startup.

Then I get 1 or 2 INFO messages like the following in my logs:

```INFO  [2016-01-26 01:40:07,221] org.apache.kafka.clients.consumer.internals.AbstractCoordinator: Attempt to heart beat failed since the group is rebalancing, try to re-join group.```

Resulting in consumption lag to be increased and after a while a portion of the consumer/partitions begin to consume messages again, some other consumer/partitions seem to never start again.

I am on the default parameters (for dispatchers). Is these a bug? or is it related to my configurations?

Please let me know with ideas/comments and if there are extra stuff you need so I could elaborate

Thanks in advance

**Comment by kciesielski** [comment]
Hi @dmtrs, are you using reactive Kafka 0.9?

**Comment by dmtrs** [comment]
@kciesielski
- Yes I am using kafka 0.9
- I am using auto commit

Yesterday I got a smooth run for about 3 hours with 1 Consumer instead of 3. 
I will try to run more tests on this.

Do you think changing the kafka thread pool options will help?

**Comment by kciesielski** [comment]
@dmtrs I don't think it's related, but if it's not a problem then why not. I'm suspecting that it's caused by this Kafka bug I pasted, unfortunately the only option to verify is to build last Kafka snapshot from sources.

**Comment by dmtrs** [comment]
@kciesielski thats exactly what I did. Running smoothly for almost an hour with rebalancing events.

For future references the steps I did where:
1. Download the `trunk` branch from `apache/kafka`
2. Build the clients package
3. Added it on my `lib/` directory (simple project for my sbt)
4. Used the following in my `build.sbt` file:
```
libraryDependencies += "org.xerial.snappy" % "snappy-java" % "1.1.1.7"
libraryDependencies += "net.jpountz.lz4" % "lz4" % "1.2.0"
libraryDependencies += "org.apache.kafka" % "kafka-clients" % "0.9.0.0" % "provided"

libraryDependencies ++= Seq(
  "com.softwaremill.reactivekafka" %% "reactive-kafka-core" % "0.9.0"
  exclude("jline", "jline")
  exclude("org.apache.kafka", "kafka-clients")
)
```

Closing the issue

**Comment by antoinetran** [comment]
Hi, we also have this issue, but with 5 minutes delay instead of 10. We found that the config "metadata.max.age.ms" with 3000ms correct this bug. Is it really a bug? Can you confirm this? Thank you.
