### ISSUE TITLE
Make the GraphStage API parts reusable

### ISSUE THREAD

**Issue by kciesielski** [softwaremill/reactive-kafka#70]
The issue has been reported by @13h3r:
The idea of graphs and graph stages are to be completely reusable. You construct you graph with shapes and nothing happens. Then you run your graph and you have an access to "runtime" stuff via materialization process.

GraphStage API in reactive kafka right now is mix of graph and runtime stuff. For example - sourceWithOffsetSink. Creation of ReactiveKafkaConsumer makes graph not reusable and breaks the contract of graphs. All runtime stuff should be created at materialization step.

**Comment by 13h3r** [comment]
in master already
