### ISSUE TITLE
Change from Decoder to Deserializer

### ISSUE THREAD

**Issue by andreaferretti** [softwaremill/reactive-kafka#74]
I see that passing from version 0.8 to 0.9 the `ConsumerProperties` are changed to take a `org.apache.kafka.common.serialization.Deserializer` instead of a `kafka.serializer.Decoder`.

It seems that the `Deserializer` API is a little more general, but I would like to understand the rationale behind the change. Is it due to an upstream change - that is, Kafka 0.9 now takes `Deserializer`s instead of `Decoder`s? I see no deprecation in the Kafka Scala API.

Moreover, if I understand correctly, the namespace `kafka` holds the Scala API, while the namespace `org.apache.kafka` holds the Java API. Does this mean that Kafka is now trying to unify the two APIs?

It is no practical problem for me to use one or the other, but I was curious what is the reason for this change, and if it has significant consequences

**Comment by kciesielski** [comment]
@andreaferretti with passing to 0.9 we wanted to get independent from Kafka itself and use only the new client API (`"org.apache.kafka" % "kafka-clients” % “0.9.0.0”`). The new client is recommended for accessing Kafka in 0.9, we also become lighter without pulling the whole Kafka library.

**Comment by andreaferretti** [comment]
Thank you, I understand. I was a little puzzled why the new API requires a `java.util.Map` in the `configure` method, while until version 0.8 Scala was a first class citizen in Kafka world
