### ISSUE TITLE
Close resources when done

### ISSUE THREAD

**Issue by andreaferretti** [softwaremill/reactive-kafka#75]
Hello, I am trying to understand how to properly close the Kafka connection when done. According to the documentation, this is done by sending the message `com.softwaremill.react.kafka.KafkaActorPublisher.Stop` to the actor in charge of reading data from Kafka.

I see two issues with this, one minor and the other major.

The minor one is that there seems not to be a way to do cleanup when using the higher level API - the only way seems to be to manually create an actor even if it is used just for this purpose.

The major one is that the message seems to be private to your codebase. Namely

```scala
import com.softwaremill.react.kafka.KafkaActorPublisher.Stop
```
results in `object KafkaActorPublisher in package kafka cannot be accessed in package com.softwaremill.react.kafka`

I think there is need to publish a version that exports this message (and possibly other that I did not find). Even better would be to add a function that sends this message internally, while only requiring clients to interact with the `KafkaPublisher`, so that one needs to resort to working with actors only if that is desired

**Comment by kciesielski** [comment]
The package private accessor will be fixed in upcoming release. As for a better API, we are moving away from the actor-based implementation, so the next major release will contain a much better one (see https://github.com/13h3r/reactive-kafka/blob/wip/api-ideas/docs/NewAPI.md)
